tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
cask "java"
brew "ammonite-repl"
brew "bat"
brew "go"
brew "dep"
brew "git"
brew "gradle"
brew "htop"
brew "python"
brew "httpie"
brew "hub"
brew "kubernetes-cli"
brew "mas"
brew "noti"
brew "python@2"
brew "shellcheck"
brew "watch"
brew "wget"
brew "wrk"
cask "appcleaner"
cask "docker"
cask "firefox"
cask "google-chrome"
cask "intellij-idea-ce"
cask "iterm2"
cask "slack"
cask "spotify"
cask "textual"
cask "visual-studio-code"
cask "zoomus"
mas "1Password 7", id: 1333542190
mas "Affinity Designer", id: 824171161
mas "Affinity Photo", id: 824183456
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Things3", id: 904280696
