"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](peach)\
$os\
$username\
[](bg:yellow fg:peach)\
$directory\
[](fg:yellow bg:teal)\
$git_branch\
$git_status\
[](fg:teal bg:blue)\
[](fg:blue bg:surface2)\
[](fg:surface2 bg:surface1)\
$time\
[ ](fg:surface1)\
$line_break$character"""

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[os]
disabled = false
style = "bg:peach fg:base"

[os.symbols]
Macos = "󰀵"

[username]
show_always = true
style_user = "bg:peach fg:base"
style_root = "bg:peach fg:base"
format = '[ $user ]($style)'

[directory]
style = "fg:base bg:yellow"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:teal"
format = '[[ $symbol $branch ](fg:base bg:teal)]($style)'

[git_status]
style = "bg:teal"
format = '[[($all_status$ahead_behind )](fg:base bg:teal)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:surface1"
format = '[[  $time ](fg:text bg:surface1)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:green)'
vimcmd_replace_one_symbol = '[](bold fg:lavender)'
vimcmd_replace_symbol = '[](bold fg:lavender)'
vimcmd_visual_symbol = '[](bold fg:yellow)'
